name: Development Check

on:
  pull_request:
    branches: ['*']

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    environment:
      name: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.1.0'

      - name: Install dependencies
        run: npm install

      - name: Type check
        run: npx tsc --noEmit

      - name: Build package
        run: npm run build

      - name: Check package contents
        run: |
          npm pack --dry-run
          echo "Package size:"
          npm pack | tail -1 | awk '{print $NF}' | xargs ls -lh

      - name: Success
        run: echo "🚧 Build successful 🚧"